/*
  C-file generated by Bin2C
  Compiled:    Oct 11 2024 at 10:28:35

  Copyright (C) 2018
  Segger Microcontroller GmbH
  www.segger.com

  The Embedded Experts
*/

static const unsigned char _acscratch08[1] =
{
    0x00, 0x00
};

/*************************** End of file ****************************/
